### ISSUE TITLE
heroku push failed cannot parse procfile 

### ISSUE THREAD

**Issue by manoj-nain** [RaviBansal7717/streamlit-opencv-demo#1]
Hi I am following your medium article to create my first streamlit app. But when pushing i get this error: "heroku push failed cannot parse procfile". I am using the same procfile as yours. Can you please help in resolving this. Thanks.

**Comment by RaviBansal7717** [comment]
Hi Manoj. Can you paste the screenshot of the error that you are getting.Then maybe it will be a bit more clear. What I will suggest is to create a new fresh file and copy contents in it, name it Procfile (P should be capital and there should be no extension not even .txt) and it should be in root directory (main folder) of your application and not in any sub folders and if the issue still persists then paste a screenshot of the error and the procfile here

**Comment by manoj-nain** [comment]
Hi Ravi i found the issue. It was simply with encoding of Procfile. Thanks for your response and great article to get me started!

**Comment by RaviBansal7717** [comment]
That's great Manoj. Good luck for your future.
